services:
# caddy é um redirecionamento de portas. Porém só deve ser usado em maquinas que já tem IP publico. Maquinas com #ip fechado que precisam de tunelamento, por exemplo, via claudflare. A própria claudflare cria as rotas, nesse #caso manter o caddy comentando para não ser usado no projeto.
#  caddy:
#    image: caddy:latest
#    container_name: caddy
#    restart: unless-stopped
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
#      - /mnt/data/caddy/data:/data  # ✅ Usando /mnt/data
#      - /mnt/data/caddy/config:/config  # ✅ Usando /mnt/data

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - /mnt/data/nextcloud/data:/var/www/html/data  # ✅ Usando /mnt/data
      - /mnt/data/nextcloud/config:/var/www/html/config  # ✅ Usando /mnt/data
    environment:
      - MYSQL_PASSWORD=${NC_DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - APACHE_DISABLE_REWRITE_IP=1 #Não obrigatório agora, mas ajuda depois com proxy reverso.

  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    volumes:
      - /mnt/data/mariadb:/var/lib/mysql  # ✅ Usando /mnt/data
    environment:
      - MARIADB_ROOT_PASSWORD=${NC_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${NC_DB_PASSWORD}
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - TZ=America/Sao_Paulo

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /mnt/data/vaultwarden:/data  # ✅ Usando /mnt/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false #Primeiro deixa True para criar a conta, após isso, deixa False e reinicia containers.

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}